title: Gunflake's IT blog
author: Vincent Nam
description: I do walk Until success.


markdown: kramdown
highlighter : rouge
permalink: /:title


url:
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
